### ISSUE TITLE
Run without repmgr

### ISSUE THREAD

**Issue by till** [bitnami/bitnami-docker-pgpool#11]
Can I use your pgpool image **without** repmgr? I need basic read-write split in fromt if a postgres cluster with one primary and one replica (streaming replication between the two).

**Comment by rafariossaa** [comment]
Hi @till,
  In our pgpool + repmgr, it also control the failover and the failback, I think this is not the same scenario  you have. Sorry.

Best regards,

**Comment by till** [comment]
Ah, okay.

So no. 😊

**Comment by danydev** [comment]
Well, actually it can be used. As long as you replicate somehow. I have your same requirement: cluster with a master and read-only streaming replica. I'm using this image to run pgpool against a (dockerized) postgresql that handles streaming replication with its own configuration (so not replication through pgpool).

`docker-compose.yml` looks like:
```
  pgpool-crs:
    image: bitnami/pgpool:4.1.4
    container_name: pgpool-crs
    hostname: pgpool-crs
    environment:
      - PGPOOL_BACKEND_NODES=0:pgsql-myapp:5432,1:pgsql-myapp-replica:5432
      # Replication disabled
      - PGPOOL_SR_CHECK_PERIOD=0
      # Needed by pgpool to identify the primary master (no actually used for replication)
      - PGPOOL_SR_CHECK_USER=www
      - PGPOOL_SR_CHECK_PASSWORD=myPwd
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=myPostgresPwd
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=myAdminPwd
      - PGPOOL_HEALTH_CHECK_USER=www
      - PGPOOL_HEALTH_CHECK_PASSWORD=myPwd
      - PGPOOL_HEALTH_CHECK_DATABASE=myDB
      - PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING=yes
```

If you do so, bitnami configuration will have `master_slave_mode = on` (that is no replication mode!)
