### ISSUE TITLE
Can't connect with custom user through pool (failed to authenticate with backend using md5)

### ISSUE THREAD

**Issue by kohanyirobert** [bitnami/bitnami-docker-pgpool#15]
**Description**

Trying to run the HA example Docker Compose config at `aaa8bd5` doesn't work as expected.
Not able to connect with `customuser:custompassword` through `pgpool`, but it works when connecting directly to `pg-0` and `pg-1`.

1. `mkdir pgpool && cd pgpool`
2. `curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-pgpool/master/docker-compose.yml > docker-compose.yml`
3. `docker-compose up -d`
4. `docker-compose exec pg-0 sh -c "PGPASSWORD=custompassword psql -h pg-0 -U customuser -d customdatabase -c 'select 1;'"` **WORKS**, please note the target host is set with `-h pg-0`.
4. docker-compose exec pg-0 sh -c "PGPASSWORD=custompassword psql -h pg-1 -U customuser -d customdatabase -c 'select 1;'" **WORKS**, please note the target host is set with `-h pg-1`.
4. `docker-compose exec pg-0 sh -c "PGPASSWORD=custompassword psql -h pgpool -U customuser -d customdatabase -c 'select 1;'"` **FAILS**, please note the target host is set with `-h pgpool`.

**Describe the results you received:**

```
psql: ERROR:  failed to authenticate with backend using md5
DETAIL:  valid password not found
```

**Describe the results you expected:**

I expected there'll be no authentication errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

`pool_passwd` doesn't contain the custom user's credentials. As described [here](https://www.pgpool.net/docs/latest/en/html/auth-pool-hba-conf.html) when using `md5` auth it should.

[`pg_md5` can be used to mitigate this](https://www.pgpool.net/docs/latest/en/html/pg-md5.html) like this.

```
docker-compose exec pgpool pg_md5 -m -f /opt/bitnami/pgpool/conf/pgpool.conf -u customuser custompassword
```

**Version**

- Output of `docker version`:

```
Docker version 19.03.1, build 74b1e89e8a
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.5   
 Storage Driver: overlay2  
  Backing Filesystem: extfs
  Supports d_type: true    
  Native Overlay Diff: true
 Logging Driver: json-file 
 Cgroup Driver: cgroupfs   
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.154-boot2docker
 Operating System: Boot2Docker 19.03.5 (TCL 10.1)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 989.5MiB
 Name: default
 ID: 6XOJ:ONSL:UDMP:K63K:B7EN:VZFZ:ERD6:MT5F:MUAX:OZWT:YH7S:3S5K
 Docker Root Dir: /mnt/sda1/var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=virtualbox
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Comment by rafariossaa** [comment]
Hi @kohanyirobert,
  Thanks for noticing this, I am opening an internal task to fix it.
  We will come back as soon as we have news.

**Comment by gholami-mohammad** [comment]
same problem

**Comment by DeoLeung** [comment]
same problem

**Comment by rafariossaa** [comment]
Hi, 
 Thanks you all, we are working in fixing this.

**Comment by foarsitter** [comment]
Took me a while to figure it out, but it is a configuration issue I suppose. 

[pgpool_generate_password_file](https://github.com/bitnami/bitnami-docker-pgpool/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L418) takes `PGPOOL_POSTGRES_USERNAME` as user to create the `pg_md5` for. 

`PGPOOL_POSTGRES_USERNAME` defaults to `postgres` in the example. 

Setting `PGPOOL_POSTGRES_USERNAME` to the same as `PGPOOL_SR_CHECK_USER` solves the issue for me.

**Comment by gholami-mohammad** [comment]
@foarsitter whould you please share your docker-compose file?

**Comment by foarsitter** [comment]
This is my working docker-compose.yml. Validate it with the commands @kohanyirobert posted. 

```
version: '2.1'
services:
  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:11-debian-10
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:11-debian-10
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
  pgpool:
    image: docker.io/bitnami/pgpool:4-debian-10
    ports:
      - 5432:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=customuser
      - PGPOOL_POSTGRES_PASSWORD=custompassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
```
