### ISSUE TITLE
docker swarm healthcheck failing

### ISSUE THREAD

**Issue by foarsitter** [bitnami/bitnami-docker-pgpool#24]
When running on a swarm with multiple nodes the health check keeps failing. When disabling the healthcheck everything runs smooth. 

The issue is resolved by using the absolute path: 
```
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
```

Does this make any sense?

If it does, I'm happily submit a pull-request.
