### ISSUE TITLE
Container failed to start with pool_hba.conf as Docker swarm service config

### ISSUE THREAD

**Issue by CaptAintHere** [bitnami/bitnami-docker-pgpool#40]
**Description**
I'm trying to deploy a Docker swarm stack fllowing [the example](https://github.com/bitnami/bitnami-docker-pgpool#using-docker-compose) given for docker-compose of this repository, but with a custom pool_hba.conf file from a Docker swarm service config.

**Steps to reproduce the issue:**

From a manager node of a Docker swarm cluster :
1. Create a Docker swarm config for `pool_hba.conf` :
```
docker config create postgresql_pool_hba.conf postgresql_pool_hba.conf
```
2. Create a Docker swarm stack using previously created config :
```
docker stack deploy -c postgresql.yml postgresql
```

Content of `postgresql_pool_hba.conf` :
```
# TYPE   DATABASE   USER         ADDRESS      METHOD
host     testdb     testuser     all          md5
```

Content of `postgresql.yml` :
```
version: "3.7"

configs:
  postgresql_pool_hba.conf:
    external: true

networks:
  internal:
    driver: overlay

services:
  pgpool:
    configs:
      - mode: 0644
        source: postgresql_pool_hba.conf
        target: /opt/bitnami/pgpool/conf/pool_hba.conf
        uid: "1001"
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.role == worker"
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: bitnami/pgpool:4
    networks:
      - internal

  pg-0:
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.role == worker"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    image: bitnami/postgresql-repmgr:13
    networks:
      - internal

  pg-1:
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.role == worker"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    image: bitnami/postgresql-repmgr:13
    networks:
      - internal
```

**Describe the results you received:**
Output of `docker logs <containerid>` :
```
pgpool 08:37:43.70
pgpool 08:37:43.71 Welcome to the Bitnami pgpool container
pgpool 08:37:43.71 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 08:37:43.71 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 08:37:43.71
pgpool 08:37:43.72 INFO  ==> ** Starting Pgpool-II setup **
pgpool 08:37:43.75 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 08:37:43.77 INFO  ==> Initializing Pgpool-II...
pgpool 08:37:43.78 INFO  ==> Generating pg_hba.conf file...
/opt/bitnami/scripts/libpgpool.sh: line 300: /opt/bitnami/pgpool/conf/pool_hba.conf: Read-only file system
```

**Describe the results you expected:**
It would be nice to detect if there is an existing `pool_hba.conf` file, and if it already exists do not attempt to create it or change its contents.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 42
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: <omitted>
  Is Manager: true
  ClusterID: <omitted>
  Managers: 3
  Nodes: 8
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: <omitted>
  Manager Addresses:
   <omitted>:2377
   <omitted>:2377
   <omitted>:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.19.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 991.1MiB
 Name: int-manager1
 ID: <omitted>
 Docker Root Dir: /mnt/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://<omitted>:5000/
 Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):

```
N/A
```
