### ISSUE TITLE
starting up the pgpool in swarm

### ISSUE THREAD

**Issue by sajusat** [bitnami/bitnami-docker-pgpool#45]
**When using the setup in docker swarm always put the pgpool container in error state.**

The pgpool container never be able to come back from the error state. 
I need to scale the service down to zero and then scale up to 1 to make it detect the pg-0 and pg-1
Is it something related to the order in which these containers start up ? what is they best way to get around this issue ?

**Steps to reproduce the issue:**

using the following docker-compose file.

```
version: "3.7"

networks:
  dbs:
    external: true

services:
  pgpool:
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.Role == worker"
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: bitnami/pgpool:4
    networks:
      - dbs

  pg-0:
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.hostname == dbnode1"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    image: bitnami/postgresql-repmgr:12
    restart: always
    volumes:
      - /tmp/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - dbs

  pg-1:
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.hostname == dbnode2"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    image: bitnami/postgresql-repmgr:12
    restart: always
    networks:
      - dbs
```
**Describe the results you received:**

```
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.21 
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.21 Welcome to the Bitnami pgpool container
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.21 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.21 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.21 
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.21 INFO  ==> ** Starting Pgpool-II setup **
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.22 INFO  ==> Validating settings in PGPOOL_* env vars...
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.24 INFO  ==> Initializing Pgpool-II...
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.24 INFO  ==> Generating pg_hba.conf file...
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.24 INFO  ==> Generating pgpool.conf file...
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.33 INFO  ==> Generating password file for local authentication...
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.34 INFO  ==> Generating password file for pgpool admin user...
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.35 INFO  ==> ** Pgpool-II setup finished! **
ejar_pgpool.1.s3ytovxk8x2h@node5    | 
ejar_pgpool.1.s3ytovxk8x2h@node5    | pgpool 08:37:28.36 INFO  ==> ** Starting Pgpool-II **
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  Backend status file /opt/bitnami/pgpool/logs/pgpool_status does not exist
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  health_check_stats_shared_memory_size: requested size: 12288
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  memory cache initialized
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: DETAIL:  memcache blocks :64
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  allocating (142682936) bytes of shared memory segment
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  allocating shared memory segment of size: 142682936 
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  health_check_stats_shared_memory_size: requested size: 12288
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  health_check_stats_shared_memory_size: requested size: 12288
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  memory cache initialized
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: DETAIL:  memcache blocks :64
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  pool_discard_oid_maps: discarded memqcache oid maps
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  Setting up socket for 0.0.0.0:5432
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  Setting up socket for :::5432
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  find_primary_node_repeatedly: waiting for finding a primary node
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: ERROR:  failed to make persistent db connection
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: DETAIL:  connection to host:"pg-0:5432" failed
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:28: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 0
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:32: pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:32: pid 1: ERROR:  failed to make persistent db connection
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:32: pid 1: DETAIL:  connection to host:"pg-1:5432" failed
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:32: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 1
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:34: pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:34: pid 1: ERROR:  failed to make persistent db connection
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:34: pid 1: DETAIL:  connection to host:"pg-0:5432" failed
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:34: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 0
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:34: pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:34: pid 1: ERROR:  failed to make persistent db connection
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:34: pid 1: DETAIL:  connection to host:"pg-1:5432" failed
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:34: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 1
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:35: pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:35: pid 1: ERROR:  failed to make persistent db connection
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:35: pid 1: DETAIL:  connection to host:"pg-0:5432" failed
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:35: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 0
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:35: pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:35: pid 1: ERROR:  failed to make persistent db connection
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:35: pid 1: DETAIL:  connection to host:"pg-1:5432" failed
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:35: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 1
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:37: pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:37: pid 1: ERROR:  failed to make persistent db connection
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:37: pid 1: DETAIL:  connection to host:"pg-0:5432" failed
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:37: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 0
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:37: pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:37: pid 1: ERROR:  failed to make persistent db connection
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:37: pid 1: DETAIL:  connection to host:"pg-1:5432" failed
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:37: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 1
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:38: pid 1: LOG:  failed to connect to PostgreSQL server on "pg-0:5432", getsockopt() failed
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:38: pid 1: DETAIL:  Operation now in progress
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:38: pid 1: ERROR:  failed to make persistent db connection
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:38: pid 1: DETAIL:  connection to host:"pg-0:5432" failed
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:38: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 0
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:38: pid 146: LOG:  failed to connect to PostgreSQL server on "pg-0:5432", getsockopt() failed
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:38: pid 146: DETAIL:  Operation now in progress
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:38: pid 146: FATAL:  failed to create a backend 0 connection
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:38: pid 146: DETAIL:  not executing failover because failover_on_backend_error is off
ejar_pgpool.1.s3ytovxk8x2h@node5    | 2021-01-02 08:37:38: pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
```

**Describe the results you expected:**

The pgpool container should be able to recover from the error state.

**Additional information you deem important (e.g. issue happens only occasionally):**

It happens all the time when I launch the setup.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:59 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:40 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: g75xqyxxoeswhmm47hp36v99j
  Is Manager: true
  ClusterID: qsr62s8y8rwrhd0r4r9m6scp4
  Managers: 3
  Nodes: 8
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.100.201
  Manager Addresses:
   192.168.100.201:2377
   192.168.100.202:2377
   192.168.100.203:2377
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-126-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 481.1MiB
 Name: node1
 ID: YQLU:ZG6W:WVVJ:4XA5:JYFZ:J6T4:X5UT:CQYQ:62OS:WAHE:3WSX:MDSX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Virtualbox VM
