### ISSUE TITLE
pgpool without replication ?

### ISSUE THREAD

**Issue by christopheblin** [bitnami/bitnami-docker-pgpool#52]
**Description**

I have an azure postgres instance reachable only from my azure K8s

There is no replication (and there is also no failover)

I'd like to put in place an "on-demand" proxy for debugging purpose (i.e create a pod with pgpool and port-forward)

At the moment, we instanciate bitnami/postgres image and we exec a bash inside with psql, but this is very unpractical compared to a full blown sql tool like dbeaver.

So I tried to use this image with minimal config (see below) but this does not work (see errors below)

My current understanding is that pgpool can be used for my use case (since it supports a single backend, as stated in the docs "If you plan to use only one PostgreSQL server, specify it by backend_hostname0.") but this image is only meant for replication use case

My questions : Can this image be used to fulfill my use case ? What would be the changes to do ?

**Steps to reproduce the issue:**

1. pod.yaml

```
apiVersion: v1
kind: Pod
metadata:
    name: pgproxy
spec:
    containers:
    - name: pgpool
      image: bitnami/pgpool:latest
      env:
      - name: PGPOOL_POSTGRES_CUSTOM_USERS
        value: "xxx@xxx"
      - name: PGPOOL_POSTGRES_CUSTOM_PASSWORDS
        value: "x"
      - name: PGPOOL_BACKEND_NODES
        value: "0:xxx.privatelink.postgres.database.azure.com"
      - name: PGPOOL_ENABLE_LDAP
        value: "no"
```

2. logs

```
% k logs pgproxy                             
pgpool 12:29:56.75 
pgpool 12:29:56.75 Welcome to the Bitnami pgpool container
pgpool 12:29:56.75 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 12:29:56.76 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 12:29:56.76 
pgpool 12:29:56.76 INFO  ==> ** Starting Pgpool-II setup **
pgpool 12:29:56.79 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 12:29:56.80 ERROR ==> The Pgpool administrator user's credentials are mandatory. Set the environment variables PGPOOL_ADMIN_USERNAME and PGPOOL_ADMIN_PASSWORD with the Pgpool administrator user's credentials.
pgpool 12:29:56.80 ERROR ==> The PostrgreSQL replication credentials are mandatory. Set the environment variables PGPOOL_SR_CHECK_USER and PGPOOL_SR_CHECK_PASSWORD with the PostrgreSQL replication credentials.
pgpool 12:29:56.80 ERROR ==> The PostrgreSQL health check credentials are mandatory. Set the environment variables PGPOOL_HEALTH_CHECK_USER and PGPOOL_HEALTH_CHECK_PASSWORD with the PostrgreSQL health check credentials.
pgpool 12:29:56.80 ERROR ==> The administrator's database credentials are required. Set the environment variables PGPOOL_POSTGRES_USERNAME and PGPOOL_POSTGRES_PASSWORD with the administrator's database credentials.
```
