### ISSUE TITLE
healthcheck.sh fails/timeout in case standby is down

### ISSUE THREAD

**Issue by zagr0** [bitnami/bitnami-docker-pgpool#53]
**Description**

Hello,

I have an issue with healthcheck.sh script used for livenessProbe of pgpool deployment in K8S (this is not postgres-ha). It gets timeout in case when standby backend from pgpool configuration is down (for example when there is maintenance or failure for the replica). That leads to pod restart and CrashLoopBackOff. Guess pgpool's helthcheck should handle normally missing one of standby backend when primary is up

**Steps to reproduce the issue:**

1. Have a postgres cluster in k8s running with replication, one primary and one standby
2. Deploy pgpool in front of postgres with `PGPOOL_BACKEND_NODES="0:<primary_service_dns>:5432:0:primary:ALWAYS_PRIMARY,1:<standby_service_dns>:5432:1:replicas"` Please check full deployment spec below.
3. Remove and keep standby pod unavailable

**Describe the results you received:**

pgpool will mark standby as down in `SHOW POOL_NODES` (this is ok and expected) but this will cause /opt/bitnami/scripts/pgpool/healthcheck.sh to timeout and CrashLoopBackOff for pgpool pods
```
$ kubectl exec -it -n postgres-dev dev-test-pgpool-5dcb95896d-7gngp -c pgpool -- /opt/bitnami/scripts/pgpool/healthcheck.sh
pgpool 15:55:26.90 INFO  ==> Checking pgpool health...
psql: timeout expired
command terminated with exit code 1
```

**Describe the results you expected:**

If there is Primary up and only standby is down healthcheck.sh should return exit code 0 to not cause any CrashLoopBackOff

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
- PostgresSQL: I'm running it in K8S with [zalando operator](https://github.com/zalando/postgres-operator), the basic setup consists of one primary and one replica and deployment provides k8s services that used to connect them
- PGPool: It's ran in K8S as a deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-test-pgpool
  namespace: postgres-dev
  labels:
    app.kubernetes.io/name: pgpool
    app.kubernetes.io/instance: test-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: pgpool
      app.kubernetes.io/instance: test-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgpool
        app.kubernetes.io/instance: test-dev
    spec:
      affinity:
        podAffinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: pgpool
                    app.kubernetes.io/instance: test-dev
                namespaces:
                  - "postgres-dev"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
      securityContext:
        fsGroup: 1001
      initContainers:
      containers:
        - name: pgpool
          image: docker.io/bitnami/pgpool:4.2.3-debian-10-r33 
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: PGPOOL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PGPOOL_BACKEND_NODES
              value: 0:dev-test.$(PGPOOL_NAMESPACE):5432:0:primary:ALWAYS_PRIMARY,1:dev-test-repl.$(PGPOOL_NAMESPACE):5432:1:replicas,
            - name: PGPOOL_SR_CHECK_USER
              valueFrom:
                secretKeyRef:
                  name: postgres.dev-test.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPOOL_SR_CHECK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.dev-test.credentials.postgresql.acid.zalan.do
                  key: password
            - name: PGPOOL_SR_CHECK_DATABASE
              value: "postgres"
            - name: PGPOOL_ENABLE_LDAP
              value: "no"
            - name: PGPOOL_POSTGRES_USERNAME
              value: "postgres"
            - name: PGPOOL_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.dev-test.credentials.postgresql.acid.zalan.do
                  key: password
            - name: PGPOOL_POSTGRES_CUSTOM_USERS
              valueFrom:
                secretKeyRef:
                  name: test-dev.dev-test.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPOOL_POSTGRES_CUSTOM_PASSWORDS
              valueFrom:
                secretKeyRef:
                  name: test-dev.dev-test.credentials.postgresql.acid.zalan.do
                  key: password
            - name: PGPOOL_ADMIN_USERNAME
              value: "admin"
            - name: PGPOOL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.dev-test.credentials.postgresql.acid.zalan.do
                  key: password
            - name: PGPOOL_ENABLE_LOAD_BALANCING
              value: "yes"
            - name: PGPOOL_ENABLE_LOG_CONNECTIONS
              value: "no"
            - name: PGPOOL_ENABLE_LOG_HOSTNAME
              value: "yes"
            - name: PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT
              value: "no"
            - name: PGPOOL_ENABLE_TLS
              value: "yes"
            - name: PGPOOL_CA_CERT_FILE
              value: /etc/ssl/ca.crt
            - name: PGPOOL_TLS_CERT_FILE
              value: /etc/ssl/tls.crt
            - name: PGPOOL_TLS_KEY_FILE
              value: /etc/ssl/tls.key
          envFrom:
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /opt/bitnami/scripts/pgpool/healthcheck.sh
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - bash
                - -ec
                - PGPASSWORD=${PGPOOL_POSTGRES_PASSWORD} psql -U "postgres" -d "postgres" -h /opt/bitnami/pgpool/tmp -tA -c "SELECT 1" >/dev/null
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits: {}
            requests: {}
          volumeMounts:
          - name: ssl-cert
            mountPath: "/etc/ssl"
            readOnly: true
      volumes:
      - name: ssl-cert
        secret:
          secretName: dev-pgpool-cert
```
