### ISSUE TITLE
ERROR:  failed to authenticate with backend using SCRAM

### ISSUE THREAD

**Issue by masteryyh** [bitnami/bitnami-docker-pgpool#68]
**Description**

I'm using docker-compose to build up a postgres cluster using bitnami/postgresql-repmgr and bitnami/pgpool. The cluster itself is working fine though, which I can connect directly using psql in the container, but pgpool always prompt this "ERROR:  failed to authenticate with backend using SCRAM DETAIL:  valid password not found". I'm pretty sure a valid username and password has been  provided by environment variables but this pgpool always seems impossible to connect to the cluster.
**Steps to reproduce the issue:**

1. [docker-compose.yml]
```
version: "3.9"

services:
  pg-0:
    image: bitnami/postgresql-repmgr:14
    container_name: pg-0
    ports:
      - 5432
    volumes:
      - ~/container/data/postgres/0:/bitnami/postgresql
    environment:
      REPMGR_NODE_NAME: pg-0
      REPMGR_NODE_NETWORK_NAME: pg-0
      REPMGR_PARTNER_NODES: pg-0,pg-1,pg-2
      REPMGR_PRIMARY_HOST: pg-0
      REPMGR_PASSWORD: repmgrpassword
      POSTGRESQL_POSTGRES_PASSWORD: postgrespassword
      POSTGRESQL_USERNAME: someusername
      POSTGRESQL_PASSWORD: somepassword
      POSTGRESQL_DATABASE: somedatabase
    restart: on-failure
    networks:
      - postgres_net
  pg-1:
    image: bitnami/postgresql-repmgr:14
    container_name: pg-1
    ports:
      - 5432
    volumes:
      - ~/container/data/postgres/1:/bitnami/postgresql
    environment:
      REPMGR_NODE_NAME: pg-1
      REPMGR_NODE_NETWORK_NAME: pg-1
      REPMGR_PARTNER_NODES: pg-0,pg-1,pg-2
      REPMGR_PRIMARY_HOST: pg-0
      REPMGR_PASSWORD: repmgrpassword
      POSTGRESQL_POSTGRES_PASSWORD: postgrespassword
      POSTGRESQL_USERNAME: someusername
      POSTGRESQL_PASSWORD: somepassword
      POSTGRESQL_DATABASE: somedatabase
    restart: on-failure
    networks:
      - postgres_net
    depends_on:
      - pg-0
  pg-2:
    image: bitnami/postgresql-repmgr:14
    container_name: pg-2
    ports:
      - 5432
    volumes:
      - ~/container/data/postgres/2:/bitnami/postgresql
    environment:
      REPMGR_NODE_NAME: pg-2
      REPMGR_NODE_NETWORK_NAME: pg-2
      REPMGR_PARTNER_NODES: pg-0,pg-1,pg-2
      REPMGR_PRIMARY_HOST: pg-0
      REPMGR_PASSWORD: repmgrpassword
      POSTGRESQL_POSTGRES_PASSWORD: postgrespassword
      POSTGRESQL_USERNAME: someusername
      POSTGRESQL_PASSWORD: somepassword
      POSTGRESQL_DATABASE: somedatabase
    restart: on-failure
    networks:
      - postgres_net
    depends_on:
      - pg-0
  pgpool:
    image: bitnami/pgpool:4
    container_name: pgpool
    ports:
      - 5432:5432
    environment:
      PGPOOL_BACKEND_NODES: 0:pg-0:5432,1:pg-1:5432,2:pg-2:5432
      PGPOOL_SR_CHECK_USER: someusername
      PGPOOL_SR_CHECK_PASSWORD: somepassword
      PGPOOL_SR_CHECK_DATABASE: somedatabase
      PGPOOL_POSTGRES_USERNAME: postgres
      PGPOOL_POSTGRES_PASSWORD: postgrespassword
      PGPOOL_ADMIN_USERNAME: someusername
      PGPOOL_ADMIN_PASSWORD: somepassword
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres_net
    depends_on:
      - pg-0
      - pg-1
      - pg-2

networks:
  postgres_net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
```
2. [compose command]
docker-compose --compatibility up -d

**Describe the results you received:**

```
2021-11-10 03:28:42: pid 156: ERROR:  failed to authenticate with backend using SCRAM
2021-11-10 03:28:42: pid 156: DETAIL:  valid password not found
```
**Describe the results you expected:**
pgpool should connect to the cluster without problems

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:58 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:42:04 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-051500-lowlatency
 Operating System: Ubuntu 21.10
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.272GiB
 Name: ubuntu-server-1
 ID: 62FE:2BX5:2IK6:EKBL:GPAO:QLF5:Y3UK:2IZX:NNSS:R5PV:VK6D:B63H
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://zmnq5n0h.mirror.aliyuncs.com/
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
Docker Compose version v2.1.0
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Kernel version:
```
Linux ubuntu-server-1 5.15.0-051500-lowlatency #202110312130 SMP PREEMPT Sun Oct 31 21:39:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
OS Version:
```
Ubuntu Server 21.10
```
and btw I'm running multiple ubuntu server 21.10 on VMware ESXi 6.7 U2
