### ISSUE TITLE
PGPOOL_ENABLE_POOL_PASSWD=no does not allow users to connect

### ISSUE THREAD

**Issue by kennedyw** [bitnami/bitnami-docker-pgpool#76]
**Description**

Setting the property PGPOOL_ENABLE_POOL_PASSWD=no appears to have no effect.

**Steps to reproduce the issue:**

Set the environment variable PGPOOL_ENABLE_POOL_PASSWD=no, full example here
```
keycloak-pgpool:
  image: bitnami/pgpool:4.2.6
  ports:
    - 5432:5432
  environment:
    - PGPOOL_BACKEND_NODES=0:keycloakpg-0:5432,1:keycloakpg-1:5432,2:keycloakpg-2:5432
    - PGPOOL_SR_CHECK_USER=postgres
    - PGPOOL_SR_CHECK_PASSWORD_FILE=/run/secrets/keycloak_postgres_root_password
    - PGPOOL_POSTGRES_USERNAME=postgres
    - PGPOOL_POSTGRES_PASSWORD_FILE=/run/secrets/keycloak_postgres_root_password
    - PGPOOL_ADMIN_USERNAME=postgres
    - PGPOOL_ADMIN_PASSWORD_FILE=/run/secrets/keycloak_postgres_root_password
    - PGPOOL_ENABLE_POOL_PASSWD=no
    - PGPOOL_MAX_POOL=64
  deploy:
    mode: replicated
    replicas: 3
    placement:
      max_replicas_per_node: 1
  secrets:
    - keycloak_postgres_root_password
    - keycloak_postgres_password
  depends_on:
    - keycloakpg-0
    - keycloakpg-1
    - keycloakpg-2
  networks:
    - keycloak
    - main
```

**Describe the results you received:**

When I attempt to connect to the pgpool instance I get:

```
keycloak_keycloak-pgpool.3.j50e8amna3rt@keycloak-db-1    | 2022-01-10 09:14:49: pid 196: WARNING:  unable to get password, password file descriptor is NULL
keycloak_keycloak-pgpool.3.j50e8amna3rt@keycloak-db-1    | 2022-01-10 09:14:49: pid 196: FATAL:  md5 authentication failed
keycloak_keycloak-pgpool.3.j50e8amna3rt@keycloak-db-1    | 2022-01-10 09:14:49: pid 196: DETAIL:  pool_passwd file does not contain an entry for "keycloak"
keycloak_keycloak-pgpool.3.j50e8amna3rt@keycloak-db-1    | 2022-01-10 09:14:49: pid 1: LOG:  child process with pid: 196 exits with status 512
keycloak_keycloak-pgpool.3.j50e8amna3rt@keycloak-db-1    | 2022-01-10 09:14:49: pid 1: LOG:  fork a new child process with pid: 215
```

**Describe the results you expected:**

I expected to be able to connect through the pgpool instance to my database with any user avaiable, in this case a user named "keycloak".

**Additional information you deem important (e.g. issue happens only occasionally):**

I would use PGPOOL_POSTGRES_CUSTOM_USERS and PGPOOL_POSTGRES_CUSTOM_PASSWORDS to specify my specific user, but I that would require me setting the passwords as plaintext which we cannot do. 

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: v1.0.22
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.10
 Git commit:        dea9396
 Built:             Thu Nov 18 00:42:51 2021
 OS/Arch:           windows/amd64
 Context:           keycloak-db-0
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    keycloak-db-0
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., v0.14.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: pzd9ag6k5o6xyoho02d0p0p73
  Is Manager: true
  ClusterID: cfxbdeu4o6220b5rldv2pdlmr
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.1.9
  Manager Addresses:
   192.168.1.9:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-92-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.84GiB
 Name: keycloak-db-0
 ID: 3YX7:ANMW:CM2W:LQ5O:KEKL:XVHQ:5YC7:2LQV:PKC2:A4HN:7RGG:JKFU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
