### ISSUE TITLE
healthcheck constantly timed out when a node fails if pgpool is only on an internal network

### ISSUE THREAD

**Issue by tusooa** [bitnami/bitnami-docker-pgpool#79]
### Name and Version

docker.io/bitnami/pgpool:4

### What steps will reproduce the bug?

0: Environment: docker swarm, single node (also reproducible on docker-compose)

1: compose file:
```
version: '3'
services:
  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:13
    networks:
      - internal
    volumes:
      - /home/test/pgpool2/data/pg-0:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-1,pg-0
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:13
    networks:
      - internal
    volumes:
      - /home/test/pgpool2/data/pg-1:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
  pgpool:
    image: docker.io/bitnami/pgpool:4
    networks:
      - internal
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  internal:
    internal: true
  external:
```

2: `docker stack deploy pgpool2`

3: check the service is running
```
] time sudo docker container exec -it $(sudo docker container ls --quiet --filter name=pgpool2_pgpool) /opt/bitnami/scripts/pgpool/healthcheck.sh
pgpool 20:51:08.75 INFO  ==> Checking pgpool health...
sudo docker container exec -it  /opt/bitnami/scripts/pgpool/healthcheck.sh  0.02s user 0.03s system 20% cpu 0.248 total
```

4: remove the standby repmgr via `sudo docker service scale pgpool2_pg-1=0`

5: run healthcheck again
```
] time sudo docker container exec -it $(sudo docker container ls --quiet --filter name=pgpool2_pgpool) /opt/bitnami/scripts/pgpool/healthcheck.sh
pgpool 20:51:37.40 INFO  ==> Checking pgpool health...
psql: timeout expired
sudo docker container exec -it  /opt/bitnami/scripts/pgpool/healthcheck.sh  0.02s user 0.05s system 0% cpu 15.231 total
```

### What is the expected behavior?

In 5, the healthcheck should finish instantly, without error.

### What do you see instead?

it took a long time to finish, and sometimes with errors (see above)

### Additional information

if I publish a port on pgpool, or connect it to the external network, this problem does not happen.

however, due to the nature of being a database, and for security considerations, I do not want to connect pgpool to the external network.

also, all psql commands will take an unbearably long time to finish.

**Comment by rafariossaa** [comment]
If you take a look to the `health_check` code [here](https://github.com/bitnami/bitnami-docker-pgpool/blob/81a851c0f4f0fdeb2045c299ccb25fbd97c4e051/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L292), you will see it is checking the nodes went back. This is going to take a little bit of time.

If you are having issues with psql, maybe it could be a networking issue in swarm.

**Comment by tusooa** [comment]
> If you take a look to the `health_check` code [here](https://github.com/bitnami/bitnami-docker-pgpool/blob/81a851c0f4f0fdeb2045c299ccb25fbd97c4e051/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L292), you will see it is checking the nodes went back. This is going to take a little bit of time.
> 
> If you are having issues with psql, maybe it could be a networking issue in swarm.

`PGCONNECT_TIMEOUT=15 PGPASSWORD="$PGPOOL_POSTGRES_PASSWORD" psql -U "$PGPOOL_POSTGRES_USERNAME" \
        -d postgres -h "$PGPOOL_TMP_DIR" -p "$PGPOOL_PORT_NUMBER" -tA -c "SHOW pool_nodes;"`

This command already takes ~10s in an internal network.

When pgpool is connected to an external network, the whole process is instant.

**Comment by tusooa** [comment]
i created an issue upstream https://github.com/moby/moby/issues/43430

**Comment by tusooa** [comment]
Again this is a huge security concern, as I definitely do not want my ISP (or anyone else) to know that one of my postgres nodes are down (because we are searching on their DNS for the hostname of that node).

**Comment by rafariossaa** [comment]
Hi,
  Not sure how is this related to `moby`. Docker has a internal DNS that resolves the containers names.

**Comment by tusooa** [comment]
> Hi, Not sure how is this related to `moby`. Docker has a internal DNS that resolves the containers names. In any case let see way the answer you.

that repo contains code for the docker engine. see https://github.com/docker/engine

**Comment by rafariossaa** [comment]
Sorry, I missed that.
Let's wait for feedback in your issue.

**Comment by tusooa** [comment]
Docker does not respond to that issue.

I have a tentative solution to this. Basically, docker will resolve any service that has at least one running container associated with it, and use the dns server specified in --dns option to resolve other names.

It seems that, this is not a proxy, but rather the container must be able to directly connect to the DNS server. But this is infeasible if the container is only on an internal network. The request will fail after a long time, and this takes too much time for the healthcheck to pass, and it is unbearably long for any possible sql connections to pgpool.

I made a fake DNS server that returns NXDOMAIN to every query ( https://lily-is.land/infra/reject-all-dns/-/blob/servant/ns.perl ). 

It turns out that, if I run the fake DNS server inside the container, and specify the DNS to be localhost, it will call that DNS server, which will immediately return NXDOMAIN and not timeout.

```
services:
  ns:
    image: ns
    networks:
      - internal
    dns: 127.0.0.1
```

```
# nslookup test
Server:         127.0.0.11
Address:        127.0.0.11#53

** server can't find test: NXDOMAIN

# nslookup test2
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   test2
Address: 10.0.1.2
```

And after `docker service scale test_test1=0`,

```
# nslookup test1
Server:         127.0.0.11
Address:        127.0.0.11#53

** server can't find test1: NXDOMAIN
````

It correctly returns NXDOMAIN instead of timing out.

Back to our issue: if we run such a DNS server inside the pgpool container, and set DNS to be localhost, I think we can work around this timeout problem.

@rafariossaa can we incorporate such thing into this image? Thank you.
